# IP5

**Joey Gladys**

**Spring 2022**

**Version 1.0**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
dataset=pd.read_csv("Self Awareness Dataset JG.csv")

In [3]:
dataset.head()

Date        Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  \
0  15-Mar    Tuesday           8              3           1           0.5   
1  16-Mar  Wednesday           6              1           1           0.5   
2  17-Mar   Thursday           6              2           0           0.0   
3  18-Mar     Friday           7              2           1           1.0   
4  19-Mar   Saturday           5              3           0           0.0   

   Work Hour  End of the day Feeling (0 to 10)  
0          0                                 8  
1          0                                 6  
2          0                                 7  
3          0                                 7  
4          0                                 5

In [4]:
dataset.isnull().sum()

Date                                0
Day                                 0
Sleep Hour                          0
Exercise Hour                       0
Study Hour                          0
StudyDS Hour                        0
Work Hour                           0
End of the day Feeling (0 to 10)    0
dtype: int64

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
dataset.columns

Index(['Date', 'Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour', 'End of the day Feeling (0 to 10)'],
      dtype='object')

In [24]:
X=dataset.iloc[::-1].values
y=dataset.iloc[:-1].values

In [33]:
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
dataset['End of the day Feeling (0 to 10)']=imputer.fit_transform(dataset[['End of the day Feeling (0 to 10)']])
dataset.isnull().sum()

Date                                0
Day                                 0
Sleep Hour                          0
Exercise Hour                       0
Study Hour                          0
StudyDS Hour                        0
Work Hour                           0
End of the day Feeling (0 to 10)    0
dtype: int64

In [34]:
X = pd.get_dummies(dataset[['Sleep Hour','Exercise Hour','Study Hour','StudyDS Hour','Work Hour']], drop_first=True)
y = pd.get_dummies(dataset[['End of the day Feeling (0 to 10)']])

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [36]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [37]:
y_pred=regressor.predict(X_test)

In [38]:
print("Coefficients", regressor.coef_)

Coefficients [[ 9.09090909e-01  9.09090909e-02  2.72727273e-01 -4.24218732e-16
   0.00000000e+00]]


In [39]:
print("intercept", regressor.intercept_)

intercept [0.18181818]


In [40]:
regressor.predict([[8,3,1,.5,0]])

array([[8.]])

In [41]:
regressor.predict([[6,1,1,.5,0]])

array([[6.]])

In [42]:
regressor.predict([[6,2,0,0,0]])

array([[5.81818182]])

In [43]:
regressor.predict([[7,2,1,1,0]])

array([[7.]])

In [45]:
regressor.predict([[5,3,0,0,0]])

array([[5.]])

In [46]:
from sklearn.metrics import r2_score
print("r2-score", r2_score(y_test,y_pred))

r2-score nan


/Users/joeygladys/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_regression.py:682: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


In [47]:
from sklearn.metrics import mean_squared_error as msc
from math import sqrt
rms=sqrt(msc(y_test,y_pred))
print("The Mean Square Error is", rms)

The Mean Square Error is 1.1818181818181808


In [48]:
import statsmodels.api as sm
X=sm.add_constant(X)

In [49]:
model=sm.OLS(y,X).fit()

In [50]:
model.summary()

/Users/joeygladys/opt/anaconda3/lib/python3.8/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/Users/joeygladys/opt/anaconda3/lib/python3.8/site-packages/statsmodels/regression/linear_model.py:1728: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
/Users/joeygladys/opt/anaconda3/lib/python3.8/site-packages/statsmodels/regression/linear_model.py:1728: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
/Users/joeygladys/opt/anaconda3/lib/python3.8/site-packages/statsmodels/regression/linear_model.py:1650: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid
/Users/joeygladys/opt/anaconda3/lib/python3.8/site-packages/st

<class 'statsmodels.iolib.summary.Summary'>
"""
                                   OLS Regression Results                                   
============================================================================================
Dep. Variable:     End of the day Feeling (0 to 10)   R-squared:                       1.000
Model:                                          OLS   Adj. R-squared:                    nan
Method:                               Least Squares   F-statistic:                       nan
Date:                              Fri, 25 Mar 2022   Prob (F-statistic):                nan
Time:                                      23:26:29   Log-Likelihood:                 159.82
No. Observations:                                 5   AIC:                            -309.6
Df Residuals:                                     0   BIC:                            -311.6
Df Model:                                         4                                         
Covariance Type:                          nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -1.0000        inf         -0        nan         nan         nan
Sleep Hour        1.5000        inf          0        nan         nan         nan
Exercise Hour    -0.5000        inf         -0        nan         nan         nan
Study Hour       -1.5000        inf         -0        nan         nan         nan
StudyDS Hour   3.553e-15        inf          0        nan         nan         nan
Work Hour              0        nan        nan        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.375
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.770
Skew:                           0.844   Prob(JB):                        0.680
Kurtosis:                       2.078   Cond. No.                         60.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.
"""